name: Ouvidoria 360 - CI (Integração Contínua)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar o código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependências do backend
        run: npm install --prefix backend

      - name: 🔍 Rodar o Linter do backend
        run: npm --prefix backend run lint

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar o código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependências do frontend
        run: npm install --prefix frontend

      - name: 🔍 Rodar o Linter do frontend
        run: npm --prefix frontend run lint

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar o código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependências do backend
        run: npm install --prefix backend

      - name: 🧪 Rodar os Testes do backend
        run: npm --prefix backend run test -- --watchAll=false

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar o código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependências do frontend
        run: npm install --prefix frontend

      - name: 🧪 Rodar os Testes do frontend
        run: npm --prefix frontend run test -- --watchAll=false

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar o código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependências do backend
        run: npm install --prefix backend

      - name: 🏗️ Testar o Build do backend
        run: npm --prefix backend run build

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar o código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependências do frontend
        run: npm install --prefix frontend

      - name: 🏗️ Testar o Build do frontend
        run: npm --prefix frontend run build